config/routes.rb
require "sidekiq/pro/web"
require "sidekiq/cron/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "monitors/lb" => "monitors#lb", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "jobs#index"

  # Lightspeed handlers
  match "/lightspeedinit", to: "lightspeedinit#index", via: [:get]
  match "/lightspeedauth", to: "lightspeedauth#index", via: [:get]

  resources :jobs do
    member do
      post :restart
    end
  end
  get "/jobs", to: "jobs#index"
  match "/google_sheets", to: "google_sheets#index", via: [:get]
  match "/google_sheets/import", to: "google_sheets#import", via: [:post]

  match "/logout", to: "sessions#destroy", as: :logout, via: [:get, :post, :delete]
  get "auth/:provider/callback", to: "sessions#create"
  resource :session, only: %i[new create destroy]

  constraints ->(request) { user_constraint(request) } do
    mount Sidekiq::Web => "/sidekiq"
  end

  def user_constraint(request)
    request.session[:id_token].present?
  end
end

app/controllers/google_sheets_controller.rb
class GoogleSheetsController < ApplicationController
  def index
    @google_sheet_tab_names = get_sheet_tab_names
  end

  def import
    tab_name = params[:tab_name]

    # TODO: Implement Google Sheets API to import data from the selected tab

    redirect_to google_sheets_path, notice: "Data import from #{tab_name} started"
  end

  private

  def get_sheet_tab_names
    SheetTabNamesService.get_tab_names
  end
end

app/views/google_sheets/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Google Sheets" %>

<h1>Google Sheets</h1>

<div class="flex flex-col mt-6">
  <div class="overflow-x-auto rounded-lg">
    <div class="inline-block min-w-full align-middle">
      <div class="overflow-hidden shadow sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="p-4 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
              Tab Name
            </th>
            <th scope="col" class="p-4 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
              Actions
            </th>
          </tr>
          </thead>
          <tbody class="bg-white">
            <% @google_sheet_tab_names.each do |tab_name| %>
              <tr>
                <td class="p-4 text-sm text-gray-900">
                  <%= tab_name %>
                </td>
                <td class="p-4 text-sm text-gray-900">
                  <%= button_to 'Import Into Woo', google_sheets_import_path(tab_name: tab_name), class: "bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-md dark:bg-gray-700 dark:text-green-400 border border-green-100 dark:border-green-500" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>