config/routes.rb
require "sidekiq/pro/web"
require "sidekiq/cron/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "monitors/lb" => "monitors#lb", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "jobs#index"

  # Lightspeed handlers
  match "/lightspeedinit", to: "lightspeedinit#index", via: [:get]
  match "/lightspeedauth", to: "lightspeedauth#index", via: [:get]

  resources :jobs do
    member do
      post :restart
    end
  end
  get "/jobs", to: "jobs#index"
  match "/google_sheets", to: "google_sheets#index", via: [:get]
  match "/google_sheets/import", to: "google_sheets#import", via: [:post]

  match "/logout", to: "sessions#destroy", as: :logout, via: [:get, :post, :delete]
  get "auth/:provider/callback", to: "sessions#create"
  resource :session, only: %i[new create destroy]

  constraints ->(request) { user_constraint(request) } do
    mount Sidekiq::Web => "/sidekiq"
  end

  def user_constraint(request)
    request.session[:id_token].present?
  end
end

app/models/job.rb
class Job < ApplicationRecord
  # Turn off single table inheritance
  self.inheritance_column = nil
  has_many :logs, foreign_key: "jobs_id", class_name: "AppLog", dependent: :destroy
  enum :status, [:created, :processing, :error, :complete, :paused], prefix: true, default: :created
  TYPE = ["WOO_IMPORT", "LS_EXTRACT", "SF_IMPORT", "WOO_REFRESH", "POLL_SHEET"]
  STATUS = ["created", "processing", "error", "complete", "paused"]

  def restart_job
    update(status: :created)
    case type
    when "WOO_IMPORT"
      WoocommerceImportJob.perform_later
    when "LS_EXTRACT"
      LightspeedExtractJob.perform_later
    when "SF_IMPORT"
      SalesforceImportJob.perform_later
    when "WOO_REFRESH"
      WoocommerceRefreshJob.perform_later
    when "POLL_SHEET"
      PollSheetJob.perform_later
    else
      false
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, except: %i[index new create]
  before_action :set_form_defaults, only: %i[new edit]

  # GET /jobs
  def index
    job_id = params[:job_id]
    type = params[:type]
    status = params[:status]
    start_date = params[:start_date]
    end_date = params[:end_date]

    q = Job.order(updated_at: :desc).includes(:logs)
    if job_id != ""
      q = q.where(id: job_id)
    end
    q = if type != ""
      q.where(type: type)
    else
      q.where.not(type: ["POLL_SHEET", "WOO_REFRESH"])
    end
    if status != ""
      q = q.where(status: status)
    end
    if start_date != ""
      q = q.where("start_date >= ?", start_date)
    end
    if end_date != ""
      q = q.where("end_date <= ?", end_date)
    end
    @jobs = q.paginate(page: params[:page], per_page: 10)
  end

  # GET /jobs/1
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @event_options = get_event_options
    @job_status = "created"
    @job_type = "LS_EXTRACT"
    @start_date_default = Date.today.last_week(:thursday)
    @end_date_default = @start_date_default + 4.days
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
    @job_status = @job.status
    @job_type = @job.type
    @start_date_default = @job.start_date
    @end_date_default = @job.end_date
  end

  # POST /jobs
  def create
    sf_job = SFImport.new.create_job(job_params[:shop_id], job_params[:start_date], job_params[:end_date])
    ls_job = LSExtract.new.create_job(job_params[:shop_id], job_params[:start_date], job_params[:end_date])

    SalesforceImportJob.perform_later
    LightspeedExtractJob.perform_later

    if sf_job.persisted? && ls_job.persisted?
      redirect_to jobs_path, notice: "Job was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    redirect_to jobs_url, notice: "Job was successfully destroyed."
  end

  # POST /jobs/1/restart
  def restart
    if @job.restart_job
      redirect_to jobs_path, notice: "Job was successfully restarted."
    else
      render :edit, status: :unprocessable_content
    end
  end

  # PATCH/PUT /jobs/1
  def update
    if @job.update!(job_params)
      redirect_to jobs_path, notice: "Job was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_content
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.expect(job: [:id, :type, :event_code, :status, :shop_id, :start_date, :end_date])
  end

  def set_form_defaults
    @job = if params[:id]
      Job.find(params[:id])
    else
      Job.new
    end
    @job.start_date = @job.start_date || params[:start_date] || Date.today.last_week(:thursday)
    @job.end_date = @job.end_date || params[:start_date] || @job.start_date + 4.days
    @job_status = @job.status || "created"
    @event_options = get_event_options
    @start_date_default = @job.start_date
    @end_date_default = @job.end_date
  end

  def get_event_options
    shops = LightspeedApiHelper.new.shops
    shops.select! { |shop| !shop.Contact["custom"].start_with?("P-") }
    shops.map { |shop| [shop.name, shop.shopID] }
  rescue Lightspeed::Error::Unauthorized => e
    Rails.logger.error "Error: #{e.message}"
    render :light_speed_error, status: :unprocessable_content
  end
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :shop_id, "Event", class: "form-label", for: 'shop_id', method: 'post' %>
    <div class="d-flex gap-2">
      <% if job.new_record? %>
        <%= form.select :shop_id, @event_options, {required: true}, {class: "form-select"} %>
      <% else %>
        <%= form.text_field :shop_id, class: 'form-control', type: 'hidden', required: true, value: @job.shop_id %>
        <%= form.text_field :event_code, class: 'form-control', type: 'text', required: true, value: @job.event_code %>
      <% end %>
    </div>
  </div>
  <div class="form-group mb-3">
    <%= form.label :type, "Type", class: "form-label", for: 'type' %>
    <div class="d-flex gap-2">
      <%= form.select :type, options_for_select(Job::TYPE, @job_type), {required: true}, {class: "form-select"} %>
    </div>
  </div>
  <div class="form-group mb-3">
    <%= form.label :status, "Status", class: "form-label", for: 'status' %>
    <div class="d-flex gap-2">
      <%= form.select :status, options_for_select(Job::STATUS, @job_status), {required: true}, {class: "form-select"} %>
    </div>
  </div>
  <div class="form-group mb-3">
    <%= form.label :start_date, "Start Date", class: "form-label", for: 'StartDate' %>
    <div class="d-flex gap-2">
      <%= form.text_field :start_date, class: 'form-control', type: 'date', required: true, value: @start_date_default %>
    </div>
  </div>
  <div class="form-group mb-3">
    <%= form.label :end_date, "End Date", class: "form-label", for: 'EndDate' %>
    <div class="d-flex gap-2">
      <%= form.text_field :end_date, class: 'form-control', type: 'date', required: true, value: @end_date_default %>
    </div>
  </div>
  <div class="form-group mb-3">
    <% if job.new_record? %>
      <%= form.submit "Create", class: "btn btn-primary" %>
    <% else %>
      <%= form.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<tr data-bs-toggle="collapse" data-bs-target="#job-logs-<%= job.id %>">
  <td><%= job.id %></td>
  <td><%= job.shop_id %></td>
  <td><%= job.event_code %></td>
  <td><%= job.type %></td>
  <td><%= job.status %></td>
  <td><%= (job.start_date) ? job.start_date.strftime("%Y-%m-%d"):'' %></td>
  <td><%= (job.end_date) ? job.end_date.strftime("%Y-%m-%d"):'' %></td>
  <td>
    <%= button_to('Edit', edit_job_path(job), method: :get, class: "btn btn-secondary btn-sm") %>
    <%= button_to('Restart', restart_job_path(job), class: "btn btn-secondary btn-sm") %>
    <%= button_to('Delete', job, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class: "btn btn-secondary btn-sm") %>
  </td>
</tr>
<% if job.logs.empty? %>
  <tr class="acollapse aaccordion-collapse" id="job-logs-<%= job.id %>" data-bs-parent=".table">
    <td></td>
    <td colspan="7" style="background-color:black !important;font-family:monospace;color:white;">No logs yet.</td>
  </tr>
<% else %>
  <tr class="acollapse aaccordion-collapse" id="job-logs-<%= job.id %>" data-bs-parent=".table">
    <td></td>
    <td colspan="7" style="background-color:black !important;font-family:monospace;color:white;">
      <% logs = job.logs.order(updated_at: :desc) %>
      <% logs = logs.limit(limit) if limit %>
      <% logs.each do |log| %>
        <%= log.content %><br />
      <% end %>
      <% if limit && job.logs.count > limit %>
        <%= link_to 'Show more', job_path(job), class: 'btn btn-secondary btn-sm' %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/jobs/edit.html.erb
<% content_for :title, "Editing job" %>

<%= render partial: 'form', locals: { job: @job } %>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Jobs" %>

<h1>Jobs</h1>

<div class="table-responsive">
<table class="table accordion table-dark">
  <thead>
  <tr>
    <th scope="col"> Job ID </th>
    <th scope="col"> Shop ID </th>
    <th scope="col"> Event Code </th>
    <th scope="col"> Type </th>
    <th scope="col"> Status </th>
    <th scope="col"> Start Date &gt;= </th>
    <th scope="col"> End Date &lt;= </th>
    <th scope="col"> Actions </th>
  </tr>
  </thead>
  <%= form_tag(jobs_path, class: 'form', method: 'GET') do |form| %>
    <tr>
      <td scope="col">
        <%= text_field_tag :job_id, params[:job_id], class: 'form-control' %>
      </td>
      <td scope="col">
        <%= text_field_tag :shop_id, params[:shop_id], class: 'form-control' %>
      </td>
      <td scope="col">
        <%= text_field_tag :event_code, params[:event_code], class: 'form-control' %>
      </td>
      <td scope="col">
        <%= select_tag :type, options_for_select(Job::TYPE, params[:type]), {include_blank: true, class: 'form-select'} %>
      </td>
      <td scope="col">
        <%= select_tag :status, options_for_select(Job::STATUS, params[:status]), {include_blank: true, class: 'form-select'} %>
      </td>
      <td scope="col">
        <%= text_field_tag :start_date, params[:start_date], class: 'form-control', type: 'date' %>
      </td>
      <td scope="col">
        <%= text_field_tag :end_date, params[:end_date], class: 'form-control', type: 'date' %>
      </td>
      <td scope="col">
        <%= submit_tag "Filter", class: "btn btn-primary" %>
      </td>
    </tr>
  <% end %>
  <tbody>
  <%= render @jobs, limit: 10 %>
  </tbody>
</table>
</div>

<nav>
<%= will_paginate @jobs, renderer: BootstrapPaginationRenderer %>
</nav>

app/views/jobs/light_speed_error.html.erb
The Lightspeed Token needs to be refreshed. Please click the "Lightspeed Auth" link above.

app/views/jobs/new.html.erb
<% content_for :title, "New job" %>

<h3 class="mb-2 text-xl font-bold text-gray-900">New Job</h3>

<%= render partial: 'form', locals: { job: @job } %>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Jobs" %>

<h1>Job <%= @job.id %></h1>

<div class="table-responsive">
  <table class="table accordion table-dark">
    <thead>
    <tr>
      <th scope="col"> Job ID </th>
      <th scope="col"> Shop ID </th>
      <th scope="col"> Event Code </th>
      <th scope="col"> Type </th>
      <th scope="col"> Status </th>
      <th scope="col"> Start Date &gt;= </th>
      <th scope="col"> End Date &lt;= </th>
      <th scope="col"> Actions </th>
    </tr>
    </thead>
    <tbody>
      <%= render @job, limit: nil %>
    </tbody>
  </table>
</div>