config/routes.rb
require "sidekiq/pro/web"
require "sidekiq/cron/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "monitors/lb" => "monitors#lb", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "jobs#index"

  # Lightspeed handlers
  match "/lightspeedinit", to: "lightspeedinit#index", via: [:get]
  match "/lightspeedauth", to: "lightspeedauth#index", via: [:get]

  resources :jobs do
    member do
      post :restart
    end
  end
  get "/jobs", to: "jobs#index"
  match "/google_sheets", to: "google_sheets#index", via: [:get]
  match "/google_sheets/import", to: "google_sheets#import", via: [:post]

  match "/logout", to: "sessions#destroy", as: :logout, via: [:get, :post, :delete]
  get "auth/:provider/callback", to: "sessions#create"
  resource :session, only: %i[new create destroy]

  constraints ->(request) { user_constraint(request) } do
    mount Sidekiq::Web => "/sidekiq"
  end

  def user_constraint(request)
    request.session[:id_token].present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="FamilyLife POS Admin Tool">
    <meta name="author" content="Cru Server Application Engineering Team">
    <title><%= content_for(:title) || "Family Life POS Admin" %></title>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#7952b3">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="text-white bg-dark">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">POS Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link"><%= link_to 'Dashboard', root_path, class: "" %></a>
            <a class="nav-link"><%= link_to 'New Job', new_job_path, class: "" %></a>
            <a class="nav-link"><%= link_to 'Lightspeed Auth', lightspeedinit_path, class: "" %></a>
            <a class="nav-link"><%= link_to 'Logout', logout_path, class: "" %></a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container mb-3">
      <div class="row justify-content-start">
        <div class="col-12">
          <div class="card text-white bg-dark">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>